<?php

/**
 * @file
 * Theme file for Skenografia sub-theme.
 */

use Drupal\bootstrap_italia\Helper\Libraries;

/**
 * Implements theme_library_info_build().
 */
function skenografia_library_info_build(): array {
  return Libraries::setLibraries();
}

// Include all files from the includes directory.
$includes_path = __DIR__ . '/includes/*.inc';

/**
 * All files in path.
 *
 * @var array<int, string>|false $files
 */
$files = glob($includes_path);

/**
 * Name of single file.
 *
 * @var string $filename
 */
foreach ((array) $files as $filename) {
  require_once __DIR__ . '/includes/' . basename($filename);
}
