<?php

/**
 * @file
 * Theme file for Bootstrap Italia.
 */

use Drupal\bootstrap_italia\Helper\Libraries;

/**
 * Implements theme_library_info_build().
 */
function skenografia_library_info_build(): array {
  return Libraries::setLibraries();
}

// Include all files from the includes directory.
$includes_path = __DIR__ . '/includes/*.inc';
foreach (glob($includes_path) as $filename) {
  require_once __DIR__ . '/includes/' . basename($filename);
}
