name: Build Release

on:
  push:
    tags:
      - '*'
#      - '/^\d+\.\d+\.\d+(-\w+)?$/'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Project
        run: |
          npm install
          npm run build:prod

      - name: Clean package
        run: |
          rm -rf .git .github node_modules .gitignore

      - name: Set timestamp
        id: timestamp
        uses: nanzm/get-time-action@master
        with:
          timeZone: CET

      - name: Versioning
        uses: "DamianReeves/write-file-action@master"
        env:
          TIMESTAMP: "${{ steps.timestamp.outputs.time }}"
        with:
          path: skenografia.info.yml
          write-mode: append
          contents: |
            
            # Information added by Github Action packaging script on ${date} 
            version: '${{  github.ref_name }}'
            project: 'skenografia'
            datestamp:

      - name: Compress Dist Folder
        run: zip -r skenografia.zip ./

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          artifacts: skenografia.zip
